var mongoose = require('mongoose');

var swatchSchema = new mongoose.Schema({
  image: {type: String},
  type: {
    type: String, 
    enum: [
      "Acetate",
      "Acrylic",
      "Alpaca",
      "Angora",
      "Antique Satin",
      "Aubusson",
      "Bamboo Fabric",
      "Bark Cloth",
      "Basket Weave",
      "Batiste",
      "Bedford Cord",
      "Bengaline",
      "Boiled Wool",
      "Boucle",
      "Broadcloth",
      "Brocade",
      "Brocatelle",
      "Burlap",
      "Burn Out Velvet",
      "Custom",
      "Calico ",
      "Cambric",
      "Camel's Hair",
      "Canvas",
      "Casement Cloth",
      "Cashmere",
      "Challis",
      "Chambray",
      "Chantilly Lace",
      "Charmuese",
      "Cheesecloth",
      "Chenille",
      "Chiffon",
      "Chintz",
      "Chite",
      "Contemporary",
      "Contract",
      "Corduroy",
      "Cotton",
      "Crepe",
      "Crepe Charmeuse",
      "Crepe de Chine",
      "Crepe-back Satin",
      "Crewel",
      "Crocheted",
      "Denim",
      "Doeskin",
      "Dotted Swiss",
      "Drill",
      "Duck Cloth",
      "Dupioni Silk",
      "Faille",
      "Faux Fur",
      "Felt",
      "Flannel",
      "Fleece",
      "Foulard",
      "Frieze",
      "Gabardine",
      "Gauze",
      "Georgette",
      "Gimp",
      "Gingham",
      "Gossamer",
      "Grois Point",
      "Grosgrain",
      "Habutai",
      "Handmade",
      "Homespun",
      "Irish Poplin",
      "Jacquard",
      "Jersey",
      "Khaki",
      "Knit",
      "La Coste",
      "Lace",
      "Lame",
      "Lawn",
      "Leather",
      "Leatherette",
      "Linen",
      "Loden Cloth",
      "Lycra",
      "Madras",
      "Marabou",
      "Matelasse",
      "Melton",
      "Merino",
      "Mesh",
      "Microfiber",
      "Mohair",
      "Moiree",
      "Moleskin",
      "Monk's Cloth",
      "Muslin",
      "Net",
      "Nylon",
      "Oilcloth",
      "Oilskin",
      "Organdy",
      "Organza",
      "Ottoman",
      "Oxford Cotton",
      "Peau de Soie",
      "Percale",
      "Pique",
      "Plisse",
      "Plush",
      "Pointelle",
      "Polyester",
      "Poplin",
      "Rayon",
      "Ripstop Nylon",
      "Sateen",
      "Satin",
      "Sequined",
      "Silk",
      "Silk Shantung",
      "Spandex",
      "Suede",
      "Surah",
      "Suzani",
      "Taffeta",
      "Tapestry",
      "Tarpaulin",
      "Terry Cloth",
      "Tweed",
      "Twill",
      "Ultrasuede",
      "Union Cloth",
      "Velour",
      "Velvet",
      "Velveteen",
      "Venice Lace",
      "Viscose",
      "Voile",
      "Waffle Cloth",
      "Wool",
      "Wool Crepe",
      "Other",
      "Unknown"
    ], 
    required: true},
  color: {
    type: String,
    enum: [
      "White",
      "Silver",
      "Gray",
      "Blue",
      "Green",
      "Orange",
      "Pink",
      "Red",
      "Purple",
      "Brown",
      "Yello",
      "Black",
      "Beige",
      "Gold",
      "Multiple",
      "Other"
    ], 
    required: true},
  quantity: {
    type: String,
    enum: [
      "1 YD",
      "2 YDS",
      "3 YDS",
      "4 YDS",
      "5 YDS",
      "6 YDS",
      "7 YDS",
      "8 YDS",
      "9 YDS",
      "10 YDS",
      "11 YDS",
      "12 YDS",
      "Bolt",
      "Hide",
      "Scrap"
    ],
    required: true},
  notes: {type: String}
}, {
  timestamps: true
});

module.exports = mongoose.model('Swatch', swatchSchema);